### PR TITLE
fix #6 update HBaseSink

### LINKED ISSUE #6: Build failed due to HBaseSink API change
Build fails with:
/gearpump-java-example/src/main/java/kafka/HBaseSinkTask.java:[53,25] error: incompatible types: String cannot be converted to UserConfig

(The api changed. The change is not reflected in the docs either: http://www.gearpump.io/releases/0.6.2/dev-connectors.html#use-of-hbasesink)

New constructor is:

```
public HBaseSink(UserConfig userconfig, String tableName, Configuration configuration) {
        this.userconfig = userconfig;
        this.tableName = tableName;
        this.configuration = configuration;
        super();
    }
```

What is the responsibility of userconfig? What should it hold?

### PR DESCRIPTION
**Pull request by huafengw**

### CODE REVIEW

**Comment by manuzhang** [comment]
+1

**Comment by clockfly** [comment]
@huafengw 

Can you make a tag?

**Comment by huafengw** [comment]
You mean this gearpump-java-template project? Do we have a version pattern for this kind of project?

**Comment by clockfly** [comment]
The version should be same as the gearpump version.

See https://github.com/gearpump/gearpump-java-example/releases

**Comment by huafengw** [comment]
Ok then.

**Pull request merged**
